#!/usr/bin/env bash

# need both yad and jq for this command to run
#
if [ ! $(which yad) ]; then
  echo "you need yad: do sudo apt install yad"
  exit 1
fi

if [ ! $(which jq) ]; then
  echo "you need jq: do sudo apt install jq"
  exit 1
fi

if [ "$1" = "-f" ]; then
  vtype=full
else
  vtype=right
fi

url='https://api.pota.app/spot/activator'

curl -s $url > temp.json 
n=$(cat temp.json | jq '. [] | {reference: .reference, activatoper: .activator, freq: .frequency}' | jq '. .reference' | wc -l)
let n=$(($n - 1))

jq 'sort_by([(.mode), (.frequency|tonumber)])' temp.json > spots.json

rm -f temp.json temp.out.txt

for s in $(seq 0 $n); do
  ref=$(cat spots.json | jq ". [$s] | .reference")
  activator=$(cat spots.json | jq ". [$s] | .activator")
  freq=$(cat spots.json | jq ". [${s}] | .frequency")
  loc=$(cat spots.json | jq ". [${s}] | .locationDesc")
  grid=$(cat spots.json | jq ". [${s}] | .grid6")
  mode=$(cat spots.json | jq ". [${s}] | .mode")

  if [ "${mode}" = '""' ]; then
    mode='n/a'
  fi
  
  # echo "strlen ${freq} ==> ${#freq}"

  if [ ${#freq} = 6 ]; then        # even though I see 4 chars, #freq reports 6
    freq="0${freq}"
  fi

  printf "FALSE %-10s %-12s %-12s %-8s %-8s %s 16\n" ${ref} ${activator} ${freq} ${mode} ${loc:0:10} ${grid} | tr -d '"' >> temp.out.txt
done

gw=$(xdpyinfo | grep dimensions | awk '{print $2}' | tr 'x' ' ' | awk '{print $1}')
gh=$(xdpyinfo | grep dimensions | awk '{print $2}' | tr 'x' ' ' | awk '{print $2}')
let h=$(($gh - 100))
let w=$(($gw - 100))

txt=( `cat temp.out.txt` )

if [ $vtype = "full" ]; then
  yad --list --checklist --print-all --width ${w} --height ${h} --escape-ok --center --column Done --column Park --column Activator --column Frequency --column Mode --column Location --column Grid --column @font@ ${txt[@]} > /dev/null 2>&1
else
  yad --list --checklist --print-all --geometry='739x980--10+-8' --escape-ok --center --column Done --column Park --column Activator --column Frequency --column Mode --column Location --column Grid --column @font@ ${txt[@]} > /dev/null 2>&1
fi

rm -f temp.out.txt
rm -f spots.json
